[package]
name = "rust-project-l1"
version = "0.1.0"
edition = "2021"

[features]
run-tests = []

[dependencies]
rand = "0.8"
tokio = { version = "1", features = ["full"] }
flume = "0.10"
tokio-util = "0.7"
dashmap = "5.0"
